arrowParens = "avoid"
printWidth = 100
proseWrap = "always"
semi = false
singleQuote = true
tabWidth = 4
trailingComma = "es5"
useTabs = true

# Markdown: https://github.com/prettier/prettier/issues/5019
[[overrides]]
files = ["*.yaml", "*.md"]
options = { singleQuote = false, tabWidth = 2 }
