[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"

[target.'cfg(all())']
rustflags = [
	# Clippy groups.
	"-Wclippy::all",
	"-Wclippy::cargo",
	"-Wclippy::nursery",
	"-Wclippy::pedantic",
	# Clippy restriction lints.
	"-Wclippy::as_conversions",
	"-Wclippy::clone_on_ref_ptr",
	"-Wclippy::empty_structs_with_brackets",
	"-Wclippy::lossy_float_literal",
	"-Wclippy::missing_docs_in_private_items",
	"-Wclippy::rest_pat_in_fully_bound_structs",
	"-Wclippy::same_name_method",
	"-Wclippy::single_char_lifetime_names",
	"-Wclippy::str_to_string",
	"-Wclippy::string_add",
	"-Wclippy::string_slice",
	"-Wclippy::string_to_string",
	"-Wclippy::todo",
	"-Wclippy::try_err",
	"-Wclippy::undocumented_unsafe_blocks",
	"-Wclippy::unnecessary_self_imports",
	"-Wclippy::unneeded_field_pattern",
	"-Wclippy::unseparated_literal_suffix",
	# Allowed Clippy lints.
	"-Aclippy::cast_possible_truncation",
	"-Aclippy::cast_sign_loss",
	"-Aclippy::equatable_if_let",
	"-Aclippy::explicit_deref_methods",
	"-Aclippy::future_not_send",
	"-Aclippy::module_inception",
	"-Aclippy::module_name_repetitions",
	"-Aclippy::option_if_let_else",
	"-Aclippy::redundant_pub_crate",
	"-Aclippy::tabs_in_doc_comments",
	# Rustdoc group.
	"-Wrustdoc::all",
	# Rust groups.
	"-Wfuture_incompatible",
	"-Wnonstandard_style",
	"-Wrust_2018_compatibility",
	"-Wrust_2018_idioms",
	"-Wrust_2021_compatibility",
	"-Wunused",
	# Rust lints.
	"-Wdeprecated_in_future",
	"-Wmacro_use_extern_crate",
	"-Wmeta_variable_misuse",
	"-Wmissing_abi",
	"-Wmissing_copy_implementations",
	"-Wmissing_debug_implementations",
	"-Wmissing_docs",
	"-Wnon_ascii_idents",
	"-Wnoop_method_call",
	"-Wsingle_use_lifetimes",
	"-Wtrivial_casts",
	"-Wtrivial_numeric_casts",
	"-Wunreachable_pub",
	"-Wunsafe_op_in_unsafe_fn",
	"-Wunstable_features",
	"-Wunused_import_braces",
	"-Wunused_lifetimes",
	"-Wunused_qualifications",
	"-Wunused_tuple_struct_fields",
]
