[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"

[target.'cfg(all())']
rustflags = [
	# Clippy groups.
	"-Wclippy::all",
	"-Wclippy::cargo",
	"-Wclippy::nursery",
	"-Wclippy::pedantic",
	# Clippy restriction lints.
	"-Wclippy::absolute_paths",
	"-Wclippy::allow_attributes",
	"-Wclippy::allow_attributes_without_reason",
	"-Wclippy::as_conversions",
	"-Wclippy::assertions_on_result_states",
	"-Wclippy::clone_on_ref_ptr",
	"-Wclippy::create_dir",
	"-Wclippy::dbg_macro",
	"-Wclippy::decimal_literal_representation",
	"-Wclippy::default_union_representation",
	"-Wclippy::empty_drop",
	"-Wclippy::empty_structs_with_brackets",
	"-Wclippy::error_impl_error",
	"-Wclippy::exit",
	"-Wclippy::filetype_is_file",
	"-Wclippy::float_cmp_const",
	"-Wclippy::fn_to_numeric_cast_any",
	"-Wclippy::format_push_string",
	"-Wclippy::get_unwrap",
	"-Wclippy::if_then_some_else_none",
	"-Wclippy::impl_trait_in_params",
	"-Wclippy::indexing_slicing",
	"-Wclippy::large_include_file",
	"-Wclippy::lossy_float_literal",
	"-Wclippy::min_ident_chars",
	"-Wclippy::missing_assert_message",
	"-Wclippy::missing_docs_in_private_items",
	"-Wclippy::mixed_read_write_in_expression",
	"-Wclippy::mutex_atomic",
	"-Wclippy::non_ascii_literal",
	"-Wclippy::partial_pub_fields",
	"-Wclippy::print_stderr",
	"-Wclippy::print_stdout",
	"-Wclippy::pub_without_shorthand",
	"-Wclippy::rc_buffer",
	"-Wclippy::rc_mutex",
	"-Wclippy::redundant_type_annotations",
	"-Wclippy::ref_patterns",
	"-Wclippy::rest_pat_in_fully_bound_structs",
	"-Wclippy::same_name_method",
	"-Wclippy::self_named_module_files",
	"-Wclippy::semicolon_outside_block",
	"-Wclippy::single_char_lifetime_names",
	"-Wclippy::str_to_string",
	"-Wclippy::string_add",
	"-Wclippy::string_lit_chars_any",
	"-Wclippy::string_slice",
	"-Wclippy::string_to_string",
	"-Wclippy::suspicious_xor_used_as_pow",
	"-Wclippy::todo",
	"-Wclippy::try_err",
	"-Wclippy::undocumented_unsafe_blocks",
	"-Wclippy::unimplemented",
	"-Wclippy::unnecessary_safety_doc",
	"-Wclippy::unnecessary_self_imports",
	"-Wclippy::unneeded_field_pattern",
	"-Wclippy::unseparated_literal_suffix",
	"-Wclippy::unwrap_used",
	"-Wclippy::use_debug",
	"-Wclippy::verbose_file_reads",
	# Allowed Clippy lints.
	"-Aclippy::equatable_if_let",
	"-Aclippy::explicit_deref_methods",
	"-Aclippy::future_not_send",
	"-Aclippy::module_inception",
	"-Aclippy::module_name_repetitions",
	"-Aclippy::option_if_let_else",
	"-Aclippy::redundant_pub_crate",
	"-Aclippy::tabs_in_doc_comments",
	# Rustdoc group.
	"-Wrustdoc::all",
	# Rust groups.
	"-Wfuture_incompatible",
	"-Wrust_2018_compatibility",
	"-Wrust_2018_idioms",
	"-Wrust_2021_compatibility",
	"-Wunused",
	# Rust lints.
	"-Wdeprecated_in_future",
	"-Wmacro_use_extern_crate",
	"-Wmeta_variable_misuse",
	"-Wmissing_abi",
	"-Wmissing_copy_implementations",
	"-Wmissing_debug_implementations",
	"-Wmissing_docs",
	"-Wnon_ascii_idents",
	"-Wsingle_use_lifetimes",
	"-Wtrivial_casts",
	"-Wtrivial_numeric_casts",
	"-Wunreachable_pub",
	"-Wunsafe_op_in_unsafe_fn",
	"-Wunused_import_braces",
	"-Wunused_lifetimes",
	"-Wunused_qualifications",
]
